baseurl: "" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "http://damirsvrtan.github.io" # the base hostname & protocol for your site
title: "Millions of Pink Lines"

# This is used by feed.xml. Uncomment if you want to use it.
# description: "..."

gems:
  - jemoji
  - jekyll-time-to-read
exclude:
  - "README.md"
  - "CHANGELOG.md"
  - "CNAME"
  - "Gemfile"
  - "Gemfile.lock"
permalink: :title
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
analytics :
  provider : google
  google :
    tracking_id : 'UA-63687498-1'
